version: "3.9"
services:
  dots-server:
    image: dotsorg/dots-server
    ports:
      - "9090:80"
    environment:
      - PORT=80
      - REGISTRY_DOMAIN=dots.rahim.li
      - DB_PATH=/app/db/dots.db
    volumes:
      - '/var/www/dots-server/archives:/app/archives/'
      - '/var/www/dots-server/db/:/app/db/'
